-- ============================================================
-- Table: categories
-- Purpose: Master lookup for course categories
-- ============================================================
-- Root-level grouping for courses
-- Hierarchy: Category → Sub-Category → Course
-- ============================================================


CREATE TABLE categories (

    -- ── Primary Key ──
    id                      BIGINT          GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    -- ── Identity ──
    code                    CITEXT          NOT NULL,
    slug                    CITEXT          NOT NULL,

    -- ── Display ──
    display_order           SMALLINT        DEFAULT 0,
    icon_url                TEXT,
    image_url               TEXT,

    -- ── Flags ──
    is_new                  BOOLEAN         NOT NULL DEFAULT FALSE,
    new_until               DATE,                                   -- auto-expire "new" badge after this date

    -- ── Audit ──
    created_by              BIGINT          REFERENCES users(id) ON DELETE SET NULL,
    updated_by              BIGINT          REFERENCES users(id) ON DELETE SET NULL,

    -- ── Status ──
    is_active               BOOLEAN         NOT NULL DEFAULT TRUE,
    is_deleted              BOOLEAN         NOT NULL DEFAULT FALSE,

    -- ── Timestamps ──
    created_at              TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at              TIMESTAMPTZ,

    -- ── Unique Constraints ──
    CONSTRAINT uq_categories_code UNIQUE (code),
    CONSTRAINT uq_categories_slug UNIQUE (slug)
);


-- ── Indexes ──

CREATE INDEX idx_categories_code ON categories (code)
    WHERE is_deleted = FALSE;

CREATE INDEX idx_categories_slug ON categories (slug)
    WHERE is_deleted = FALSE;

CREATE INDEX idx_categories_display_order ON categories (display_order)
    WHERE is_deleted = FALSE AND is_active = TRUE;

CREATE INDEX idx_categories_active ON categories (is_active)
    WHERE is_deleted = FALSE;


-- ── Full-Text Search Indexes (pg_trgm) ──

CREATE INDEX idx_categories_content_trgm
    ON categories
    USING GIN ((COALESCE(code::TEXT, '') || ' ' || COALESCE(slug::TEXT, '')) gin_trgm_ops);


-- ── Trigger: auto-slug ──
CREATE TRIGGER trg_categories_slug
    BEFORE INSERT OR UPDATE ON categories
    FOR EACH ROW
    EXECUTE FUNCTION fn_auto_slug('code');

-- ── Trigger: updated_at ──
CREATE TRIGGER trg_categories_updated_at
    BEFORE UPDATE ON categories
    FOR EACH ROW
    EXECUTE FUNCTION fn_update_updated_at_column();


-- ── Comments ──


-- ══════════════════════════════════════════════
-- Seed Data (15 real-world course categories)
-- Modeled after: Udemy, Coursera, LinkedIn Learning
-- slug auto-generated by fn_auto_slug('code')
-- ══════════════════════════════════════════════

INSERT INTO categories (code, slug, display_order, is_new, is_active) VALUES
    ('CAT-DEV',         'development',              1,  FALSE, TRUE),
    ('CAT-DATA',        'data-science',             2,  FALSE, TRUE),
    ('CAT-AI',          'artificial-intelligence',  3,  TRUE,  TRUE),
    ('CAT-CLOUD',       'cloud-computing',          4,  FALSE, TRUE),
    ('CAT-CYBER',       'cyber-security',           5,  FALSE, TRUE),
    ('CAT-DESIGN',      'design',                   6,  FALSE, TRUE),
    ('CAT-BUSINESS',    'business',                 7,  FALSE, TRUE),
    ('CAT-MARKETING',   'digital-marketing',        8,  FALSE, TRUE),
    ('CAT-FINANCE',     'finance-accounting',       9,  FALSE, TRUE),
    ('CAT-PM',          'project-management',       10, FALSE, TRUE),
    ('CAT-MOBILE',      'mobile-development',       11, FALSE, TRUE),
    ('CAT-DEVOPS',      'devops',                   12, FALSE, TRUE),
    ('CAT-DB',          'database',                 13, FALSE, TRUE),
    ('CAT-SOFT',        'soft-skills',              14, FALSE, TRUE),
    ('CAT-LANGUAGE',    'language-learning',        15, FALSE, TRUE)
ON CONFLICT DO NOTHING;


-- ============================================================
-- Table: category_translations
-- Purpose: Multi-language content for categories
-- ============================================================
-- FK: category_id → categories (RESTRICT)
-- FK: language_id → languages (RESTRICT)
-- UNIQUE: one translation per category per language
-- ============================================================


CREATE TABLE category_translations (

    -- ── Primary Key ──
    id                      BIGINT          GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    -- ── Relationships ──
    category_id             BIGINT          NOT NULL REFERENCES categories(id) ON DELETE RESTRICT,
    language_id             BIGINT          NOT NULL REFERENCES languages(id) ON DELETE RESTRICT,

    -- ── Content ──
    name                    CITEXT          NOT NULL,
    description             TEXT,
    is_new_title            TEXT,                                   -- custom "New" badge label per language

    -- ── Media ──
    icon                    TEXT,
    image                   TEXT,

    -- ── Tags ──
    tags                    JSONB           DEFAULT '[]'::JSONB,

    -- ── SEO: Meta ──
    meta_title              TEXT,
    meta_description        TEXT,
    meta_keywords           TEXT,
    canonical_url           TEXT,

    -- ── SEO: Open Graph ──
    og_site_name            TEXT,
    og_title                TEXT,
    og_description          TEXT,
    og_type                 TEXT,
    og_image                TEXT,
    og_url                  TEXT,

    -- ── SEO: Twitter Card ──
    twitter_site            TEXT,
    twitter_title           TEXT,
    twitter_description     TEXT,
    twitter_image           TEXT,
    twitter_card            TEXT            DEFAULT 'summary_large_image',

    -- ── SEO: Other ──
    robots_directive        TEXT            DEFAULT 'index,follow',
    focus_keyword           TEXT,

    -- ── Full-Text Search ──
    search_vector           TSVECTOR        GENERATED ALWAYS AS (
        setweight(to_tsvector('simple', coalesce(name, '')), 'A') ||
        setweight(to_tsvector('simple', coalesce(description, '')), 'B') ||
        setweight(to_tsvector('simple', coalesce(meta_title, '')), 'A') ||
        setweight(to_tsvector('simple', coalesce(meta_description, '')), 'B') ||
        setweight(to_tsvector('simple', coalesce(focus_keyword, '')), 'A') ||
        setweight(to_tsvector('simple', coalesce(tags::TEXT, '')), 'D')
    ) STORED,

    -- ── Structured Data ──
    structured_data         JSONB           DEFAULT '[]'::JSONB,

    -- ── Audit ──
    created_by              BIGINT          REFERENCES users(id) ON DELETE SET NULL,
    updated_by              BIGINT          REFERENCES users(id) ON DELETE SET NULL,

    -- ── Status ──
    is_active               BOOLEAN         NOT NULL DEFAULT TRUE,
    is_deleted              BOOLEAN         NOT NULL DEFAULT FALSE,

    -- ── Timestamps ──
    created_at              TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at              TIMESTAMPTZ,

    -- ── Unique Constraint ──
    CONSTRAINT uq_category_translations_cat_lang UNIQUE (category_id, language_id)
);


-- ── Indexes ──

CREATE INDEX idx_category_translations_category ON category_translations (category_id)
    WHERE is_deleted = FALSE;

CREATE INDEX idx_category_translations_language ON category_translations (language_id)
    WHERE is_deleted = FALSE;

CREATE INDEX idx_category_translations_name ON category_translations USING gin (name gin_trgm_ops)
    WHERE is_deleted = FALSE;

CREATE INDEX idx_category_translations_search ON category_translations USING gin (search_vector);

CREATE INDEX idx_category_translations_tags ON category_translations USING gin (tags)
    WHERE is_deleted = FALSE;

CREATE INDEX idx_category_translations_active ON category_translations (is_active)
    WHERE is_deleted = FALSE;


-- ── Full-Text Search Indexes (pg_trgm) ──

CREATE INDEX idx_category_translations_content_trgm
    ON category_translations
    USING GIN ((COALESCE(name::TEXT, '') || ' ' || COALESCE(description::TEXT, '')) gin_trgm_ops);


-- ── Trigger: updated_at ──
-- ── Trigger: backfill parent slug from translation name ──
CREATE TRIGGER trg_category_translations_backfill_slug
    AFTER INSERT ON category_translations
    FOR EACH ROW
    EXECUTE FUNCTION fn_backfill_slug('categories', 'category_id', 'name');

CREATE TRIGGER trg_category_translations_updated_at
    BEFORE UPDATE ON category_translations
    FOR EACH ROW
    EXECUTE FUNCTION fn_update_updated_at_column();


-- ── Comments ──
