-- ============================================================
-- Table: sub_categories
-- Purpose: Master lookup for course sub-categories
-- ============================================================
-- FK: category_id → categories (RESTRICT)
-- Hierarchy: Category → Sub-Category → Course
-- ============================================================


CREATE TABLE sub_categories (

    -- ── Primary Key ──
    id                      BIGINT          GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    -- ── Relationships ──
    category_id             BIGINT          NOT NULL REFERENCES categories(id) ON DELETE RESTRICT,

    -- ── Identity ──
    code                    CITEXT          NOT NULL,
    slug                    CITEXT          NOT NULL,

    -- ── Display ──
    display_order           SMALLINT        DEFAULT 0,
    icon_url                TEXT,
    image_url               TEXT,

    -- ── Flags ──
    is_new                  BOOLEAN         NOT NULL DEFAULT FALSE,
    new_until               DATE,

    -- ── Audit ──
    created_by              BIGINT          REFERENCES users(id) ON DELETE SET NULL,
    updated_by              BIGINT          REFERENCES users(id) ON DELETE SET NULL,

    -- ── Status ──
    is_active               BOOLEAN         NOT NULL DEFAULT TRUE,
    is_deleted              BOOLEAN         NOT NULL DEFAULT FALSE,

    -- ── Timestamps ──
    created_at              TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at              TIMESTAMPTZ,

    -- ── Unique Constraints ──
    CONSTRAINT uq_sub_categories_category_slug UNIQUE (category_id, slug)
);


-- ── Indexes ──

CREATE INDEX idx_sub_categories_category ON sub_categories (category_id)
    WHERE is_deleted = FALSE;

CREATE INDEX idx_sub_categories_code ON sub_categories (code)
    WHERE is_deleted = FALSE;

CREATE INDEX idx_sub_categories_slug ON sub_categories (slug)
    WHERE is_deleted = FALSE;

CREATE INDEX idx_sub_categories_display_order ON sub_categories (category_id, display_order)
    WHERE is_deleted = FALSE AND is_active = TRUE;

CREATE INDEX idx_sub_categories_active ON sub_categories (is_active)
    WHERE is_deleted = FALSE;

CREATE INDEX idx_sub_categories_category_active ON sub_categories (category_id, is_active)
    WHERE is_deleted = FALSE;


-- ── Full-Text Search Indexes (pg_trgm) ──

CREATE INDEX idx_sub_categories_content_trgm
    ON sub_categories
    USING GIN ((COALESCE(code::TEXT, '') || ' ' || COALESCE(slug::TEXT, '')) gin_trgm_ops);


-- ── Trigger: auto-slug ──
CREATE TRIGGER trg_sub_categories_slug
    BEFORE INSERT OR UPDATE ON sub_categories
    FOR EACH ROW
    EXECUTE FUNCTION fn_auto_slug('code');

-- ── Trigger: updated_at ──
CREATE TRIGGER trg_sub_categories_updated_at
    BEFORE UPDATE ON sub_categories
    FOR EACH ROW
    EXECUTE FUNCTION fn_update_updated_at_column();


-- ── Comments ──


-- ══════════════════════════════════════════════
-- Seed Data (60 real-world sub-categories)
-- Modeled after: Udemy, Coursera, LinkedIn Learning
-- slug auto-generated by fn_auto_slug('code')
-- category_id references categories seed order
-- ══════════════════════════════════════════════

INSERT INTO sub_categories (category_id, code, slug, display_order, is_active) VALUES

    -- ── CAT-DEV (1) — Development ──
    (1,  'SCAT-WEB-DEV',        'web-development',              1,  TRUE),
    (1,  'SCAT-BACKEND',        'backend-development',          2,  TRUE),
    (1,  'SCAT-FRONTEND',       'frontend-development',         3,  TRUE),
    (1,  'SCAT-FULLSTACK',      'full-stack-development',       4,  TRUE),
    (1,  'SCAT-API-DEV',        'api-development',              5,  TRUE),
    (1,  'SCAT-GAME-DEV',       'game-development',             6,  TRUE),

    -- ── CAT-DATA (2) — Data Science ──
    (2,  'SCAT-DATA-ANALYSIS',  'data-analysis',                1,  TRUE),
    (2,  'SCAT-DATA-VIZ',       'data-visualization',           2,  TRUE),
    (2,  'SCAT-BIG-DATA',       'big-data',                     3,  TRUE),
    (2,  'SCAT-DATA-ENG',       'data-engineering',             4,  TRUE),

    -- ── CAT-AI (3) — Artificial Intelligence ──
    (3,  'SCAT-ML',             'machine-learning',             1,  TRUE),
    (3,  'SCAT-DL',             'deep-learning',                2,  TRUE),
    (3,  'SCAT-NLP',            'natural-language-processing',  3,  TRUE),
    (3,  'SCAT-COMPUTER-VISION','computer-vision',              4,  TRUE),
    (3,  'SCAT-GEN-AI',         'generative-ai',                5,  TRUE),

    -- ── CAT-CLOUD (4) — Cloud Computing ──
    (4,  'SCAT-AWS',            'amazon-web-services',          1,  TRUE),
    (4,  'SCAT-AZURE',          'microsoft-azure',              2,  TRUE),
    (4,  'SCAT-GCP',            'google-cloud-platform',        3,  TRUE),
    (4,  'SCAT-CLOUD-ARCH',     'cloud-architecture',           4,  TRUE),

    -- ── CAT-CYBER (5) — Cyber Security ──
    (5,  'SCAT-ETH-HACK',      'ethical-hacking',              1,  TRUE),
    (5,  'SCAT-NET-SEC',        'network-security',             2,  TRUE),
    (5,  'SCAT-APP-SEC',        'application-security',         3,  TRUE),
    (5,  'SCAT-COMPLIANCE',     'compliance-governance',        4,  TRUE),

    -- ── CAT-DESIGN (6) — Design ──
    (6,  'SCAT-UI-UX',         'ui-ux-design',                 1,  TRUE),
    (6,  'SCAT-GRAPHIC',       'graphic-design',                2,  TRUE),
    (6,  'SCAT-WEB-DESIGN',    'web-design',                    3,  TRUE),
    (6,  'SCAT-MOTION',        'motion-graphics',               4,  TRUE),

    -- ── CAT-BUSINESS (7) — Business ──
    (7,  'SCAT-ENTREPRENEUR',  'entrepreneurship',              1,  TRUE),
    (7,  'SCAT-STRATEGY',      'business-strategy',             2,  TRUE),
    (7,  'SCAT-OPERATIONS',    'operations-management',         3,  TRUE),
    (7,  'SCAT-STARTUP',       'startup-building',              4,  TRUE),

    -- ── CAT-MARKETING (8) — Digital Marketing ──
    (8,  'SCAT-SEO',           'search-engine-optimization',    1,  TRUE),
    (8,  'SCAT-SEM',           'search-engine-marketing',       2,  TRUE),
    (8,  'SCAT-SOCIAL',        'social-media-marketing',        3,  TRUE),
    (8,  'SCAT-CONTENT',       'content-marketing',             4,  TRUE),
    (8,  'SCAT-EMAIL-MKT',    'email-marketing',               5,  TRUE),

    -- ── CAT-FINANCE (9) — Finance & Accounting ──
    (9,  'SCAT-ACCOUNTING',    'accounting',                    1,  TRUE),
    (9,  'SCAT-FIN-ANALYSIS',  'financial-analysis',            2,  TRUE),
    (9,  'SCAT-INVEST',        'investing-trading',             3,  TRUE),
    (9,  'SCAT-TAXATION',      'taxation',                      4,  TRUE),

    -- ── CAT-PM (10) — Project Management ──
    (10, 'SCAT-AGILE',         'agile-scrum',                   1,  TRUE),
    (10, 'SCAT-PMP',           'pmp-certification',             2,  TRUE),
    (10, 'SCAT-PRODUCT',       'product-management',            3,  TRUE),

    -- ── CAT-MOBILE (11) — Mobile Development ──
    (11, 'SCAT-ANDROID',       'android-development',           1,  TRUE),
    (11, 'SCAT-IOS',           'ios-development',               2,  TRUE),
    (11, 'SCAT-FLUTTER',       'flutter-development',           3,  TRUE),
    (11, 'SCAT-REACT-NATIVE',  'react-native',                  4,  TRUE),

    -- ── CAT-DEVOPS (12) — DevOps ──
    (12, 'SCAT-DOCKER',        'docker',                        1,  TRUE),
    (12, 'SCAT-K8S',           'kubernetes',                    2,  TRUE),
    (12, 'SCAT-CI-CD',         'ci-cd-pipelines',               3,  TRUE),
    (12, 'SCAT-IAC',           'infrastructure-as-code',        4,  TRUE),

    -- ── CAT-DB (13) — Database ──
    (13, 'SCAT-SQL',           'sql',                           1,  TRUE),
    (13, 'SCAT-POSTGRESQL',    'postgresql',                    2,  TRUE),
    (13, 'SCAT-MONGODB',       'mongodb',                       3,  TRUE),
    (13, 'SCAT-DB-DESIGN',     'database-design',               4,  TRUE),

    -- ── CAT-SOFT (14) — Soft Skills ──
    (14, 'SCAT-COMMUNICATION', 'communication-skills',          1,  TRUE),
    (14, 'SCAT-LEADERSHIP',    'leadership',                    2,  TRUE),
    (14, 'SCAT-INTERVIEW',     'interview-preparation',         3,  TRUE),
    (14, 'SCAT-PRODUCTIVITY',  'productivity',                  4,  TRUE),

    -- ── CAT-LANGUAGE (15) — Language Learning ──
    (15, 'SCAT-ENGLISH',       'english',                       1,  TRUE),
    (15, 'SCAT-HINDI',         'hindi',                         2,  TRUE),
    (15, 'SCAT-JAPANESE',      'japanese',                      3,  TRUE),
    (15, 'SCAT-GERMAN',        'german',                        4,  TRUE)

ON CONFLICT DO NOTHING;


-- ============================================================
-- Table: sub_category_translations
-- Purpose: Multi-language content for sub-categories
-- ============================================================
-- FK: sub_category_id → sub_categories (RESTRICT)
-- FK: language_id → languages (RESTRICT)
-- UNIQUE: one translation per sub-category per language
-- ============================================================


CREATE TABLE sub_category_translations (

    -- ── Primary Key ──
    id                      BIGINT          GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    -- ── Relationships ──
    sub_category_id         BIGINT          NOT NULL REFERENCES sub_categories(id) ON DELETE RESTRICT,
    language_id             BIGINT          NOT NULL REFERENCES languages(id) ON DELETE RESTRICT,

    -- ── Content ──
    name                    CITEXT          NOT NULL,
    description             TEXT,
    is_new_title            TEXT,

    -- ── Media ──
    icon                    TEXT,
    image                   TEXT,

    -- ── Tags ──
    tags                    JSONB           DEFAULT '[]'::JSONB,

    -- ── SEO: Meta ──
    meta_title              TEXT,
    meta_description        TEXT,
    meta_keywords           TEXT,
    canonical_url           TEXT,

    -- ── SEO: Open Graph ──
    og_site_name            TEXT,
    og_title                TEXT,
    og_description          TEXT,
    og_type                 TEXT,
    og_image                TEXT,
    og_url                  TEXT,

    -- ── SEO: Twitter Card ──
    twitter_site            TEXT,
    twitter_title           TEXT,
    twitter_description     TEXT,
    twitter_image           TEXT,
    twitter_card            TEXT            DEFAULT 'summary_large_image',

    -- ── SEO: Other ──
    robots_directive        TEXT            DEFAULT 'index,follow',
    focus_keyword           TEXT,

    -- ── Full-Text Search ──
    search_vector           TSVECTOR        GENERATED ALWAYS AS (
        setweight(to_tsvector('simple', coalesce(name, '')), 'A') ||
        setweight(to_tsvector('simple', coalesce(description, '')), 'B') ||
        setweight(to_tsvector('simple', coalesce(meta_title, '')), 'A') ||
        setweight(to_tsvector('simple', coalesce(meta_description, '')), 'B') ||
        setweight(to_tsvector('simple', coalesce(focus_keyword, '')), 'A') ||
        setweight(to_tsvector('simple', coalesce(tags::TEXT, '')), 'D')
    ) STORED,

    -- ── Structured Data ──
    structured_data         JSONB           DEFAULT '[]'::JSONB,

    -- ── Audit ──
    created_by              BIGINT          REFERENCES users(id) ON DELETE SET NULL,
    updated_by              BIGINT          REFERENCES users(id) ON DELETE SET NULL,

    -- ── Status ──
    is_active               BOOLEAN         NOT NULL DEFAULT TRUE,
    is_deleted              BOOLEAN         NOT NULL DEFAULT FALSE,

    -- ── Timestamps ──
    created_at              TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at              TIMESTAMPTZ,

    -- ── Unique Constraint ──
    CONSTRAINT uq_sub_category_translations_sub_cat_lang UNIQUE (sub_category_id, language_id)
);


-- ── Indexes ──

CREATE INDEX idx_sub_category_translations_sub_cat ON sub_category_translations (sub_category_id)
    WHERE is_deleted = FALSE;

CREATE INDEX idx_sub_category_translations_language ON sub_category_translations (language_id)
    WHERE is_deleted = FALSE;

CREATE INDEX idx_sub_category_translations_name ON sub_category_translations USING gin (name gin_trgm_ops)
    WHERE is_deleted = FALSE;

CREATE INDEX idx_sub_category_translations_search ON sub_category_translations USING gin (search_vector);

CREATE INDEX idx_sub_category_translations_tags ON sub_category_translations USING gin (tags)
    WHERE is_deleted = FALSE;

CREATE INDEX idx_sub_category_translations_active ON sub_category_translations (is_active)
    WHERE is_deleted = FALSE;


-- ── Full-Text Search Indexes (pg_trgm) ──

CREATE INDEX idx_sub_category_translations_content_trgm
    ON sub_category_translations
    USING GIN ((COALESCE(name::TEXT, '') || ' ' || COALESCE(description::TEXT, '')) gin_trgm_ops);


-- ── Trigger: updated_at ──
-- ── Trigger: backfill parent slug from translation name ──
CREATE TRIGGER trg_sub_category_translations_backfill_slug
    AFTER INSERT ON sub_category_translations
    FOR EACH ROW
    EXECUTE FUNCTION fn_backfill_slug('sub_categories', 'sub_category_id', 'name');

CREATE TRIGGER trg_sub_category_translations_updated_at
    BEFORE UPDATE ON sub_category_translations
    FOR EACH ROW
    EXECUTE FUNCTION fn_update_updated_at_column();


-- ── Comments ──
