import { Router } from 'express';

import authRoutes from './auth/auth.routes';
import healthRoutes from './health/health.routes';
import rolePermissionsRoutes from './junctions/role-permissions.routes';
import userPermissionsRoutes from './junctions/user-permissions.routes';
import branchDepartmentsRoutes from './resources/branch-departments.routes';
import branchesRoutes from './resources/branches.routes';
import categoriesRoutes from './resources/categories.routes';
import citiesRoutes from './resources/cities.routes';
import countriesRoutes from './resources/countries.routes';
import departmentsRoutes from './resources/departments.routes';
import designationsRoutes from './resources/designations.routes';
import documentTypesRoutes from './resources/document-types.routes';
import employeeProfilesRoutes from './employee-profiles/employee-profiles.routes';
import instructorProfilesRoutes from './instructor-profiles/instructor-profiles.routes';
import documentsRoutes from './resources/documents.routes';
import educationLevelsRoutes from './resources/education-levels.routes';
import languagesRoutes from './resources/languages.routes';
import learningGoalsRoutes from './resources/learning-goals.routes';
import permissionsRoutes from './resources/permissions.routes';
import rolesRoutes from './resources/roles.routes';
import skillsRoutes from './resources/skills.routes';
import socialMediasRoutes from './resources/social-medias.routes';
import specializationsRoutes from './resources/specializations.routes';
import studentProfilesRoutes from './student-profiles/student-profiles.routes';
import statesRoutes from './resources/states.routes';
import subCategoriesRoutes from './resources/sub-categories.routes';
import userDocumentsRoutes from './user-documents/user-documents.routes';
import userEducationRoutes from './user-education/user-education.routes';
import userExperienceRoutes from './user-experience/user-experience.routes';
import userLanguagesRoutes from './user-languages/user-languages.routes';
import userProfilesRoutes from './user-profiles/user-profiles.routes';
import userProjectsRoutes from './user-projects/user-projects.routes';
import userSkillsRoutes from './user-skills/user-skills.routes';
import userSocialMediasRoutes from './user-social-medias/user-social-medias.routes';
import subjectsRoutes from './subjects/subjects.routes';
import chaptersRoutes from './chapters/chapters.routes';
import topicsRoutes from './topics/topics.routes';
import subTopicsRoutes from './sub-topics/sub-topics.routes';
import bundleCoursesRoutes from './bundle-courses/bundle-courses.routes';
import bundlesRoutes from './bundles/bundles.routes';
import courseChaptersRoutes from './course-chapters/course-chapters.routes';
import courseInstructorsRoutes from './course-instructors/course-instructors.routes';
import courseModulesRoutes from './course-modules/course-modules.routes';
import courseModuleTopicsRoutes from './course-module-topics/course-module-topics.routes';
import courseSubCategoriesRoutes from './course-sub-categories/course-sub-categories.routes';
import courseSubjectsRoutes from './course-subjects/course-subjects.routes';
import coursesRoutes from './courses/courses.routes';
import mcqQuestionsRoutes from './mcq-questions/mcq-questions.routes';
import mcqQuestionTranslationsRoutes from './mcq-question-translations/mcq-question-translations.routes';
import mcqOptionsRoutes from './mcq-options/mcq-options.routes';
import mcqOptionTranslationsRoutes from './mcq-option-translations/mcq-option-translations.routes';
import oneWordQuestionsRoutes from './one-word-questions/one-word-questions.routes';
import oneWordQuestionTranslationsRoutes from './one-word-question-translations/one-word-question-translations.routes';
import oneWordSynonymsRoutes from './one-word-synonyms/one-word-synonyms.routes';
import oneWordSynonymTranslationsRoutes from './one-word-synonym-translations/one-word-synonym-translations.routes';
import descriptiveQuestionsRoutes from './descriptive-questions/descriptive-questions.routes';
import descriptiveQuestionTranslationsRoutes from './descriptive-question-translations/descriptive-question-translations.routes';
import matchingQuestionsRoutes from './matching-questions/matching-questions.routes';
import matchingQuestionTranslationsRoutes from './matching-question-translations/matching-question-translations.routes';
import matchingPairsRoutes from './matching-pairs/matching-pairs.routes';
import matchingPairTranslationsRoutes from './matching-pair-translations/matching-pair-translations.routes';
import orderingQuestionsRoutes from './ordering-questions/ordering-questions.routes';
import orderingQuestionTranslationsRoutes from './ordering-question-translations/ordering-question-translations.routes';
import orderingItemsRoutes from './ordering-items/ordering-items.routes';
import orderingItemTranslationsRoutes from './ordering-item-translations/ordering-item-translations.routes';
import usersRoutes from './users/users.routes';
import assessmentsRoutes from './assessments/assessments.routes';
import assessmentAttachmentsRoutes from './assessment-attachments/assessment-attachments.routes';
import assessmentSolutionsRoutes from './assessment-solutions/assessment-solutions.routes';
import webinarsRoutes from './webinars/webinars.routes';
import courseBatchesRoutes from './course-batches/course-batches.routes';
import instructorPromotionsRoutes from './instructor-promotions/instructor-promotions.routes';
import referralCodesRoutes from './referral-codes/referral-codes.routes';
import couponsRoutes from './coupons/coupons.routes';

// ═══════════════════════════════════════════════════════════════
// v1 router aggregator.
// Additional module routers will be mounted here as modules land.
// ═══════════════════════════════════════════════════════════════

const v1Router = Router();

v1Router.use('/health', healthRoutes);
v1Router.use('/auth', authRoutes);
v1Router.use('/countries', countriesRoutes);
v1Router.use('/states', statesRoutes);
v1Router.use('/cities', citiesRoutes);
v1Router.use('/skills', skillsRoutes);
v1Router.use('/languages', languagesRoutes);
v1Router.use('/education-levels', educationLevelsRoutes);
v1Router.use('/document-types', documentTypesRoutes);
v1Router.use('/documents', documentsRoutes);
v1Router.use('/designations', designationsRoutes);
v1Router.use('/specializations', specializationsRoutes);
v1Router.use('/learning-goals', learningGoalsRoutes);
v1Router.use('/social-medias', socialMediasRoutes);
v1Router.use('/categories', categoriesRoutes);
v1Router.use('/sub-categories', subCategoriesRoutes);
v1Router.use('/roles', rolesRoutes);
v1Router.use('/permissions', permissionsRoutes);
v1Router.use('/role-permissions', rolePermissionsRoutes);
v1Router.use('/user-permissions', userPermissionsRoutes);
v1Router.use('/branches', branchesRoutes);
v1Router.use('/departments', departmentsRoutes);
v1Router.use('/branch-departments', branchDepartmentsRoutes);
v1Router.use('/users', usersRoutes);
v1Router.use('/employee-profiles', employeeProfilesRoutes);
v1Router.use('/student-profiles', studentProfilesRoutes);
v1Router.use('/instructor-profiles', instructorProfilesRoutes);
v1Router.use('/user-profiles', userProfilesRoutes);
v1Router.use('/user-education', userEducationRoutes);
v1Router.use('/user-experience', userExperienceRoutes);
v1Router.use('/user-social-medias', userSocialMediasRoutes);
v1Router.use('/user-skills', userSkillsRoutes);
v1Router.use('/user-languages', userLanguagesRoutes);
v1Router.use('/user-documents', userDocumentsRoutes);
v1Router.use('/user-projects', userProjectsRoutes);
v1Router.use('/subjects', subjectsRoutes);
v1Router.use('/chapters', chaptersRoutes);
v1Router.use('/topics', topicsRoutes);
v1Router.use('/sub-topics', subTopicsRoutes);
v1Router.use('/bundle-courses', bundleCoursesRoutes);
v1Router.use('/bundles', bundlesRoutes);
v1Router.use('/course-chapters', courseChaptersRoutes);
v1Router.use('/course-instructors', courseInstructorsRoutes);
v1Router.use('/course-module-topics', courseModuleTopicsRoutes);
v1Router.use('/course-modules', courseModulesRoutes);
v1Router.use('/course-sub-categories', courseSubCategoriesRoutes);
v1Router.use('/course-subjects', courseSubjectsRoutes);
v1Router.use('/courses', coursesRoutes);
v1Router.use('/mcq-questions', mcqQuestionsRoutes);
v1Router.use('/mcq-question-translations', mcqQuestionTranslationsRoutes);
v1Router.use('/mcq-options', mcqOptionsRoutes);
v1Router.use('/mcq-option-translations', mcqOptionTranslationsRoutes);
v1Router.use('/one-word-questions', oneWordQuestionsRoutes);
v1Router.use('/one-word-question-translations', oneWordQuestionTranslationsRoutes);
v1Router.use('/one-word-synonyms', oneWordSynonymsRoutes);
v1Router.use('/one-word-synonym-translations', oneWordSynonymTranslationsRoutes);
v1Router.use('/descriptive-questions', descriptiveQuestionsRoutes);
v1Router.use('/descriptive-question-translations', descriptiveQuestionTranslationsRoutes);
v1Router.use('/matching-questions', matchingQuestionsRoutes);
v1Router.use('/matching-question-translations', matchingQuestionTranslationsRoutes);
v1Router.use('/matching-pairs', matchingPairsRoutes);
v1Router.use('/matching-pair-translations', matchingPairTranslationsRoutes);
v1Router.use('/ordering-questions', orderingQuestionsRoutes);
v1Router.use('/ordering-question-translations', orderingQuestionTranslationsRoutes);
v1Router.use('/ordering-items', orderingItemsRoutes);
v1Router.use('/ordering-item-translations', orderingItemTranslationsRoutes);
v1Router.use('/assessments', assessmentsRoutes);
v1Router.use('/assessments/:assessmentId/attachments', assessmentAttachmentsRoutes);
v1Router.use('/assessments/:assessmentId/solutions', assessmentSolutionsRoutes);
v1Router.use('/webinars', webinarsRoutes);
v1Router.use('/course-batches', courseBatchesRoutes);
v1Router.use('/instructor-promotions', instructorPromotionsRoutes);
v1Router.use('/referral-codes', referralCodesRoutes);
v1Router.use('/coupons', couponsRoutes);

export default v1Router;
